name: ✅ CI

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library.yml@4.0.0
    with:
      library: libhal-armcortex
    secrets: inherit

  cortex-m0:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.0.0
    with:
      profile: cortex-m0
    secrets: inherit

  cortex-m0plus:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.0.0
    with:
      profile: cortex-m0plus
    secrets: inherit

  cortex-m1:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.0.0
    with:
      profile: cortex-m1
    secrets: inherit

  cortex-m3:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.0.0
    with:
      profile: cortex-m3
    secrets: inherit

  cortex-m4:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.0.0
    with:
      profile: cortex-m4
    secrets: inherit

  cortex-m4f:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.0.0
    with:
      profile: cortex-m4f
    secrets: inherit

  release:
    needs:
      [
        ci,
        cortex-m0,
        cortex-m0plus,
        cortex-m1,
        cortex-m3,
        cortex-m4,
        cortex-m4f,
      ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
