name: 🚀 Deploy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  cortex-m0:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@3.0.1
    with:
      profile: cortex-m0
    secrets: inherit

  cortex-m0plus:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@3.0.1
    with:
      profile: cortex-m0plus
    secrets: inherit

  cortex-m1:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@3.0.1
    with:
      profile: cortex-m1
    secrets: inherit

  cortex-m3:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@3.0.1
    with:
      profile: cortex-m3
    secrets: inherit

  cortex-m4:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@3.0.1
    with:
      profile: cortex-m4
    secrets: inherit

  cortex-m4f:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@3.0.1
    with:
      profile: cortex-m4f
    secrets: inherit
